### ISSUE TITLE
Wrong color on Dark+ (WoW) theme

### ISSUE THREAD

**Issue by m4xc4v413r4** [Septh/vscode-wow-bundle#2]
I'm having a problem with the Dark+ (WoW) theme.

![code_2017-02-04_01-47-43](https://cloud.githubusercontent.com/assets/3492333/22614585/f0730aac-ea7b-11e6-813d-aabfc44cfdbc.jpg)

On your example, the black text is actually white, which makes sense because black on dark background is strange xD
I went to check if I could find the reason and fix it/commit before I came here but I honestly don't see anything with the code for black or very dark.

btw, i'm making some snippets for personal use (some general lua and some more for addons), if you want i can send them after for you to include on the extension.

Thank you for your work.

**Comment by Septh** [comment]
Interesting. This happens only with the latest VS Code version (1.9) - which I only installed today (I was "off coding" for a while :) I'll start working on it ASAP. Thanks for the report.

**Comment by Septh** [comment]
Ok, found and updated. Release 1.1.10 should fix the problem - please let me know if everything is fine.

**Comment by m4xc4v413r4** [comment]
Everything great man, thanks :)

btw, I have 60 snippets basically done, just missing description.
Donno if you would want to include them on your extension, if you do let me know and i'll finish them asap and send you.

Another thing, I don't know how your VSC setup is while doing addons, maybe i'm not telling you anything new, but I'm using https://github.com/dcr30/vscode-lualinter with https://github.com/cogwheel/lua-wow to AT LEAST get errors so I don't waste my time looking for a wild comma out of place and stuff like that xD
Not sure if that lua-wow is up-to-date since it's pretty old but it shouldn't be off by a lot if anything since the lua functions modified by blizzard don't really get updated all that often.

This could be a start on having a linter on the extension also :)

**Comment by Septh** [comment]
I'd be more than happy to include any snippet you may have - it's definitely something I'm willing to have in the bundle, only too short of time to do it myself. If you can submit a pull request here on Github that would be great; otherwise, we'll sort out a way. :)

Same goes for the linter. I'm well aware of vscode-lualinter (though not using it - don't ask me why, I don't have any reason. Shame on me) and this is really the next improvement I intend to make to the bundle. Again, time is actually the rarest resource in my life so... any help you can provide will be much appreciated :)
